apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation

on:
  push:
    branches:
      - "**"

jobs:
  build:
    steps:
      # - name: action test
      #   uses: calculi-corp/ng-dsl-example/.cloudbees/actions/hello-action
      #   with:
      #     arg-1: |
      #       Optimus Prime
      - uses: cloudbees-io/checkout@v1
      - name: echo
        uses: docker://golang:1.20
        run: |
          set -eo pipefail
          echo "trigger run - 1"
