apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - "**"

jobs:
  build:
    steps:
      - name: action test
        uses: calculi-corp/ng-dsl-example/.cloudbees/actions/hello-action
        with:
          arg-1: |
            Optimus Prime
      - name: get-source-code
        uses: cloudbees-io/checkout@v1
